schema_version = "1.0.0"

id = "material_x"
type = "add-on"
version = "0.1.1"

name = "MaterialX Import/Export"
tagline = "Import and export Blender materials to/from MaterialX"
maintainer = "Michal Hons | info@mehpixel.com"
website = "https://github.com/Tweekazoid/bl_mtlx"

tags = ["3D View"]
blender_version_min = "3.0.0"

license = ["SPDX:GPL-2.0-or-later"]

[permissions]
files = "Import downloaded assets into the scene"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "*.pyc",
  "*.pyo",
  "/.*",
  "*.zip",
  "VERSION",
]
